### ISSUE TITLE
prisma migrate dev fails in MySQL

### ISSUE THREAD

**Issue by maneko00** [Shopify/shopify-app-template-remix#308]
## OverView

I am using MySQL on [Prisma](https://www.prisma.io/).
When I run prisma migrate dev, I encounter migration failure with error message "Prisma Migrate could not create the shadow database.

I followed [this procedure](https://shopify.dev/docs/apps/deployment/web) to deploy to Heroku.
version ```"prisma": "^4.13.0"```

---
## Reproduction procedures

Open the following file in your editor and enter the contents.

prisma/schema.prisma
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Session {
  id          String    @id
  shop        String
  state       String
  isOnline    Boolean   @default(false)
  scope       String?
  expires     DateTime?
  accessToken String
  userId      BigInt?
}
```

Dockerfile
```dockerfile
FROM node:18-alpine

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
EXPOSE 3000
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

RUN npx prisma migrate dev --name init

CMD ["npm", "run", "start"]

```
heroku.yml
```yml
build:
  docker:
    web: Dockerfile
  config:
    SHOPIFY_API_KEY: SHOPIFY_API_KEY   # <-- Actually, the value is directly inserted.
    DATABASE_URL: DATABASE_URL          # <-- Actually, the value is directly inserted.
```

Push the app to Heroku. This will automatically build the docker image and deploy the app:
```
git push heroku main
```

Verify that the migration fails and the following error message is displayed.
```
Error: P3014

Prisma Migrate could not create the shadow database. 
Please make sure the database user has permission to create databases. 
Read more about the shadow database (and workarounds) at https://pris.ly/d/migrate-shadow

Original error: Error code: P1010

User `prisma_user` was denied access on the database `prisma_db`
```
---
## Checked

I have looked at the following article to see how to fix the problem, but could not figure out how to incorporate it into my environment.

https://github.com/prisma/prisma/issues/4571
https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database
